-- 테스트용 테이블 생성
CREATE TABLE TB_TEST(
	TEST_NO NUMBER PRIMARY KEY,
	TEST_TITLE VARCHAR2(100) NOT NULL,
	TEST_CONTENT VARCHAR2(500) NOT NULL
);

SELECT * FROM TB_TEST;

UPDATE TB_TEST SET
TEST_TITLE = '제목1임', TEST_CONTENT='내용1임'
WHERE TEST_NO=1;

ROLLBACK;
COMMIT;


SELECT EMP_ID, EMP_NAME, JOB_NAME, SALARY
FROM EMPLOYEE
LEFT JOIN JOB USING (JOB_CODE)
WHERE JOB_NAME = '대리'
AND SALARY > ANY (SELECT MIN(SALARY)
					FROM EMPLOYEE
					WHERE JOB_NAME = '과장');