--ADD 1.
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, ENTRANCE_DATE 입학일자
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY 1;

--ADD 2.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3;

--ADD 3.
SELECT PROFESSOR_NAME 교수이름, (2022-(PROFESSOR_SSN)) 나이
FROM TB_PROFESSOR
ORDER BY DESC;

--ADD 4.
SELECT SUBSTR(PROFESSOR_NAME,2) 이름
FROM TB_PROFESSOR;

--ADD 5.
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_SSN,1,6)-ENTRANCE_DATE != 19;  