-- BASIC 1.
SELECT DEPARTMENT_NAME 학과명, CATEGORY 계열
FROM TB_DEPARTMENT;

-- BASIC 2.
SELECT DEPARTMENT_NAME ||'의 정원은 '|| CAPACITY ||' 입니다.' "학과별 정원"
FROM TB_DEPARTMENT;

--BAISC 3.
SELECT STUDENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE TB_DEPARTMENT.DEPARTMENT_NAME = '국어국문학과'
AND SUBSTR(STUDENT_SSN, 8,1)='2'
AND ABSENCE_YN = 'Y';

--BASIC 4.
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119');

--BASIC 5.
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY >=20 AND CAPACITY <=30;

--BASIC 6.
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

--BASIC 7.
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NAME IS NULL;

--BASIC 8.
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

--BAISC 9.
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT;

--BAISC 10.
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE STUDENT_NO LIKE 'A2%'
AND STUDENT_ADDRESS LIKE '%전주%'
AND ABSENCE_YN = 'N';

