--ADD 1.
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, TO_CHAR(ENTRANCE_DATE ,'YYYY-MM-DD') 입학일자
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY 1;


--ADD 2.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3;


--ADD 3.
SELECT PROFESSOR_NAME 교수이름, 
	ROUND((SYSDATE-TO_DATE( SUBSTR(PROFESSOR_SSN,1,INSTR(PROFESSOR_SSN,'-')-1)))/365) 나이
FROM TB_PROFESSOR
ORDER BY PROFESSOR_SSN DESC;


--ADD 4.
SELECT SUBSTR(PROFESSOR_NAME,2) 이름
FROM TB_PROFESSOR;


--????
--ADD 5.
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT; 


--???
--ADD 6.
SELECT TO_CHAR(2020-12-25,'YYYY-MM-DD DAY') 크리스마스
FROM DUAL;


--ADD 7-1.YY
SELECT TO_DATE('99/10/11', 'YY/MM/DD'), TO_DATE('49/10/11', 'YY/MM/DD')
FROM DUAL;
--ADD 7-2.RR
SELECT TO_DATE('99/10/11', 'RR/MM/DD'), TO_DATE('49/10/11', 'RR/MM/DD')
FROM DUAL;


--ADD 8.
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO NOT LIKE 'A%';


--ADD 9.
SELECT ROUND(AVG(POINT),1) 학점
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178'


--ADD 10.
SELECT DEPARTMENT_NO 학과번호, COUNT(*) "학생수(명)"
FROM TB_DEPARTMENT
JOIN TB_STUDENT USING (DEPARTMENT_NO)
GROUP BY DEPARTMENT_NO
ORDER BY 1;


--ADD 11.
SELECT COUNT(*)
FROM TB_STUDENT
WHERE  COACH_PROFESSOR_NO IS NULL;


--????
--ADD 12.
SELECT SUBSTR(TERM_NO,1,4) 년도, ROUND(AVG(POINT),1) "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY TERM_NO
ORDER BY TERM_NO;


--????
--ADD 13.
SELECT DEPARTMENT_NO 학과코드명, ABSENCE_YN 휴학생 수
FROM TB_STUDENT
WHERE ABSENCE_YN 'Y'
GROUP BY DEPARTMENT_NO;


--????
--ADD 14.
SELECT STUDENT_NAME, COUNT(*) "동명이인 수"
FROM TB_STUDENT
WHERE COUNT(STUDENT_NAME = STUDENT_NAME);


--???
--ADD 15.
SELECT SUBSTR(TERM_N0,1,4) 년도, SUBSTR(TERM_NO, 5) 학기, POINT 평점
FROM TB_GRADE
GROUP BY TERM_N0;